controllers/ClientController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Sirkuler;
use app\models\SirkulerSearch;
use app\models\User;
use app\models\Unit;
use app\models\JenisKontrak;
use app\models\History;
use app\models\HistorySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\filters\AccessControl;
use app\components\AccessRule;
use yii\web\ForbiddenHttpException;
use yii\base\Model;
use aryelds\sweetalert\SweetAlert;

/**
 * SirkulerController implements the CRUD actions for Sirkuler model.
 */
class ClientController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {

        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['client'],
                    ],

                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionHome()
    {
        return $this->render('home');
    }

    /**
     * Lists all Sirkuler models.
     * @return mixed
     */
    public function actionIndex()
    {
        
        $searchModel = new SirkulerSearch();        
        
        if (\Yii::$app->user->can('reviewer')) {
            $query = Sirkuler::find()->where(['status_id'=> [2,3,4,5,6,99]]);          
        } else if (\Yii::$app->user->can('user')){
            $userId = Yii::$app->User->id;
            $query = Sirkuler::find()->where(['submit_user'=> $userId]);
        } else if (\Yii::$app->user->can('approver')){
            $userId = Yii::$app->User->id;
            $query = Sirkuler::find()->where(['approver_id'=> $userId,'status_id'=>[3,4,5,6,99]]);
        }

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$query);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Sirkuler model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $history = new History();
        $count = 3;

        if ($history->load(Yii::$app->request->post())) {
            
            for ($i=1 ; $i <= $count; $i++){
                $doc = UploadedFile::getInstance($history, "document_name[$i]");
                if (!is_null($doc)) {
                    $history->sirkuler_id = $model->id;
                    $history->user_id = Yii::$app->user->getId();
                    $history->document_status_id = 2;
                    $history->document_revision = 0;
                    $history->document_type_id = $i;        
                    $history->date = time();

                    $history->document_status_id = 2;
                    $history->document_status_id = 2;
                    $history->document_scr = $doc->name;
                    $tmp = explode(".", $doc->name);
                    $ext = end($tmp);
                    // generate a unique file name to prevent duplicate filenames
                    $history->document_name = Yii::$app->security->generateRandomString(6).".{$ext}";                            
                    // the path to save file, you can set an uploadPath
                    // in Yii::$app->params (as used in example below)                       
                    Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web/uploads/sirkuler/';
                    $path = Yii::$app->params['uploadPath'] . $history->document_name;
                    $doc->saveAs($path);

                    $history->save();
                }
            }

            // $newhistory = History::find()->where(['sirkuler_id' => 82,'document_status_id'=>2]);
            $newhistory = History::find()->where(['sirkuler_id'=>$id,'document_status_id'=>2]);
            $countstatus = $newhistory->count();

            if($countstatus == $count){
                for ($y=1 ; $y <= $count; $y++){
                    $check = History::find()->where(['sirkuler_id'=>$id,'document_type_id'=> $y,'document_status_id'=>2])->one();
                    $check->document_status_id = 3;
                    $check->save();
                    $hi = $check->document_status_id;
                    $ss = Sirkuler::findOne($id);
                    $ss->status_id = 2;
                    $ss->save();
                }
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }


        return $this->render('view', [
            'model' => $model,
            'history' => $history,

        ]);
    }

    /**
     * Creates a new Sirkuler model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */

    public function actionCreate()
    {
        // if(Yii::$app->user->can('create-kontrak')) { 
            //Find out how many document have been submitted by the form
            // $count = count(Yii::$app->request->post('History', []));
            $count = 9;

            //Send at least one model to the form
            $documents = [];

            //Create an array of the documents submitted
            for($i = 1; $i <= $count; $i++) {
                $documents[] = new History();
            }

            $model  = new Sirkuler();
            
    
            if ($model->load(Yii::$app->request->post()) && Model::loadMultiple($documents, Yii::$app->request->post())) {
                
                $model->submit_user = Yii::$app->user->getId();
                $model->submit_date = time();
                $model->approver_id = 1;
                $model->status_id = 1;
                $model->save();

                $nill = 0;  
                $status = 1;              

                foreach ($documents as $index => $document){
                    $docs = UploadedFile::getInstance($document, "[$index]document_name");
                    
                    if(is_null($docs)){
                        $nill++;
                    }
                }

                if ($nill == 0){
                    $status = 3;
                    $model->status_id = 2;
                    $model->save();
                } 


                foreach ($documents as $index => $document)
                {
                    $document->sirkuler_id = $model->id;
                    $document->user_id = $model->submit_user;
                    $document->document_status_id = $status;
                    $document->document_revision = 0;
                    $document->document_type_id = $index+1;        
                    $document->date = time();

                    $doc = UploadedFile::getInstance($document, "[$index]document_name");

                        if (!is_null($doc)) {
                            $document->document_status_id = 2;
                            $document->document_status_id = 2;
                            $document->document_scr = $doc->name;
                            $tmp = explode(".", $doc->name);
                            $ext = end($tmp);
                            // generate a unique file name to prevent duplicate filenames
                            $document->document_name = Yii::$app->security->generateRandomString(6).".{$ext}";                            
                            // the path to save file, you can set an uploadPath
                            // in Yii::$app->params (as used in example below)                       
                            Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web/uploads/sirkuler/';
                            $path = Yii::$app->params['uploadPath'] . $document->document_name;
                            $doc->saveAs($path);
                        }

                    $document->save();
                }
                
                if ($model->save()) {            
                    return $this->redirect(['view', 'id' => $model->id]);             
                }  else {
                    var_dump ($model->getErrors()); 
                    var_dump ($documents->getErrors());
                    
                    die();
                }
            }
                return $this->render('create', [
                'model' => $model,
                'documents' => $documents,
                ]);   
        // } else {
        //     throw new ForbiddenHttpException;
        // }
    }

    

    /**
     * Updates an existing Sirkuler model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        // if (!Yii::$app->user->can('update-kontrak',['id' => $model])){
        //     throw new ForbiddenHttpException;
        // }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Sirkuler model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**

views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;
use aryelds\sweetalert\SweetAlert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
            );
        echo SweetAlert::widget();
        ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= SweetAlert::widget(); ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.0
    </div>
    <strong>Copyright &copy; 2020 <a href="https://telkom.co.id">PT. Telkom Indonesia</a></strong> All rights
    reserved.
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-waring pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->

        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right"/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

views/layouts/header.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;


/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">APP</span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">

                <!-- Messages: style can be found in dropdown.less-->

                <!-- User Account: style can be found in dropdown.less -->
                <li class="user user-menu">
                <a href="<?= Url::toRoute('/user/settings/account');?>">
                        <?= Html::img('@web/uploads/avatar/'.Yii::$app->User->identity->avatar, 
                            ['alt' => 'avatar','class'=>'user-image']) 
                        ?>
                        <!-- <img src="<?= $directoryAsset ?>/img/user3-128x128.jpg" class="user-image" alt="User Image"/> -->
                        <span class="hidden-xs"><?= Yii::$app->User->identity->name ?></span>
                    </a>
                </li>
                <!-- User Account: style can be found in dropdown.less -->
                <li>

                <li class="logout" style="margin-right: 50px">
                    <?= Html::a('Logout', ['/user/security/logout'],['data-method' => 'post']) ?>
                </li>
                <!-- User Account: style can be found in dropdown.less -->
                <li>
                    
                </li>
            </ul>
        </div>
    </nav>
</header>

views/layouts/left.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use mdm\admin\components\MenuHelper;
use mdm\admin\components\Helper;
use yii\bootstrap\Nav;


/* @var $this \yii\web\View */
/* @var $content string */


?>

<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <?= Html::img('@web/uploads/avatar/'.Yii::$app->User->identity->avatar, 
                    ['alt' => 'avatar','class'=>'img-circle']) 
                ?>
                <!-- <img src="<?= $directoryAsset ?>/img/user3-128x128.jpg" class="img-circle" alt="User Image"/> -->
            </div>
            <div class="pull-left info">
                <p><?= Yii::$app->User->identity->name ?></p>

                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->

        

        <?php

            $menuItems = [
                ['label' => 'Application List', 'options' => ['class' => 'header']],
                ['label' => 'Dashboard','icon' => ' fa fa-dashboard','url' => ['/client/home']],
                ['label' => 'Dashboard','icon' => ' fa fa-dashboard','url' => ['/reviewer/home']],
                ['label' => 'Dashboard','icon' => ' fa fa-dashboard','url' => ['/approver/home']],

                ['label' => 'Daftar Kontrak','icon' => ' fa-file-text','url' => ['/client/index']],
                ['label' => 'Daftar Kontrak','icon' => ' fa-file-text','url' => ['/reviewer/index']],
                ['label' => 'Daftar Kontrak','icon' => ' fa-file-text','url' => ['/approver/index']],

                ['label' => 'Buat Kontrak','icon' => ' fa-plus-circle','url' => ['/client/create']],

                ['label' => 'Debug','icon' => ' fa-bug','url' => ['/debug']],
                ['label' => 'RBAC','icon' => ' fa-user','url' => ['/admin']],
                
            ];

            $menuItems = Helper::filter($menuItems);

            echo dmstr\widgets\Menu::widget([
                'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                'items' => $menuItems,
            ]);

        ?>

        <?php
        
        // dmstr\widgets\Menu::widget(
            // [
            //     'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
            //     'items' => [
            //         ['label' => 'Application List', 'options' => ['class' => 'header']],
            //         ['label' => 'Dashboard', 'icon' => ' fa fa-dashboard', 'url' => ['/site']],
            //         ['label' => 'Daftar Kontrak', 'icon' => ' fa-file-text', 'url' => ['/sirkuler']],
            //         ['label' => 'Buat Kontrak Baru', 'icon' => ' fa-plus-circle', 'url' => ['/sirkuler/create']],
                    // ['label' => 'Debug', 'icon' => 'dashboard', 'url' => ['/debug']],
                    // Yii::$app->user->isGuest ?
                    //     ['label' => 'Sign in', 'url' => ['/user/security/login']] :
                    // [
                    //     'label' => 'Some tools',
                    //     'icon' => 'share',
                    //     'url' => '#',
                    //     'items' => [
                    //         ['label' => 'Gii', 'icon' => 'file-code-o', 'url' => ['/gii'],],
                    //         ['label' => 'Debug', 'icon' => 'dashboard', 'url' => ['/debug'],],
                    //         [
                    //             'label' => 'Level One',
                    //             'icon' => 'circle-o',
                    //             'url' => '#',
                    //             'items' => [
                    //                 ['label' => 'Level Two', 'icon' => 'circle-o', 'url' => '#',],
                    //                 [
                    //                     'label' => 'Level Two',
                    //                     'icon' => 'circle-o',
                    //                     'url' => '#',
                    //                     'items' => [
                    //                         ['label' => 'Level Three', 'icon' => 'circle-o', 'url' => '#',],
                    //                         ['label' => 'Level Three', 'icon' => 'circle-o', 'url' => '#',],
                    //                     ],
                    //                 ],
                    //             ],
                    //         ],
                            
                    //     ],
                    // ],
                    
        //         ],
        //     ]
        // ) 
        ?>

    </section>

</aside>

views/layouts/main-login.php
<?php
use app\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page" 
      style="background-image:url('<?= Yii::$app->urlManager->baseUrl . '/img/tlt.jpg'?>');
             background-size:cover">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


if (Yii::$app->controller->action->id === 'login' || Yii::$app->controller->action->id === 'register') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="hold-transition <?= \dmstr\helpers\AdminLteHelper::skinClass() ?> sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'left.php',
            ['directoryAsset' => $directoryAsset]
        )
        ?>

        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>